#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
# autospec version: v2
# autospec commit: f032afc
#
Name     : python-openzwave
Version  : 0.4.19
Release  : 38
URL      : https://github.com/OpenZWave/python-openzwave/archive/v0.4.19/python-openzwave-0.4.19.tar.gz
Source0  : https://github.com/OpenZWave/python-openzwave/archive/v0.4.19/python-openzwave-0.4.19.tar.gz
Source1  : https://raw.githubusercontent.com/OpenZWave/python-openzwave/master/archives/open-zwave-master-0.4.9.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 GPL-3.0 ISC LGPL-3.0
Requires: python-openzwave-bin = %{version}-%{release}
Requires: python-openzwave-license = %{version}-%{release}
Requires: python-openzwave-python = %{version}-%{release}
Requires: python-openzwave-python3 = %{version}-%{release}
Requires: pypi(cython)
Requires: pypi(pydispatcher)
Requires: pypi(pyserial)
Requires: pypi(six)
BuildRequires : buildreq-distutils3
BuildRequires : libopenzwave-dev
BuildRequires : pypi(cython)
BuildRequires : pypi(pydispatcher)
BuildRequires : python3-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Relax-Cython-version-pinning.patch

%description
.. image:: https://travis-ci.org/OpenZWave/python-openzwave.svg?branch=master
:target: https://travis-ci.org/OpenZWave/python-openzwave
:alt: Travis status

%package bin
Summary: bin components for the python-openzwave package.
Group: Binaries
Requires: python-openzwave-license = %{version}-%{release}

%description bin
bin components for the python-openzwave package.


%package license
Summary: license components for the python-openzwave package.
Group: Default

%description license
license components for the python-openzwave package.


%package python
Summary: python components for the python-openzwave package.
Group: Default
Requires: python-openzwave-python3 = %{version}-%{release}

%description python
python components for the python-openzwave package.


%package python3
Summary: python3 components for the python-openzwave package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-openzwave package.


%prep
%setup -q -n python-openzwave-0.4.19
cd %{_builddir}
unzip -q %{_sourcedir}/open-zwave-master-0.4.9.zip
cd %{_builddir}/python-openzwave-0.4.19
mkdir -p openzwave-embed/open-zwave-master
cp -r %{_builddir}/open-zwave-master/* %{_builddir}/python-openzwave-0.4.19/openzwave-embed/open-zwave-master
%patch -P 1 -p1
pushd ..
cp -a python-openzwave-0.4.19 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697575481
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
CLEAR_INTERMEDIATE_CXXFLAGS=$CLEAR_INTERMEDIATE_CFLAGS
CLEAR_INTERMEDIATE_FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
CLEAR_INTERMEDIATE_FCFLAGS=$CLEAR_INTERMEDIATE_FFLAGS
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
CLEAR_INTERMEDIATE_CXXFLAGS=$CLEAR_INTERMEDIATE_CFLAGS
CLEAR_INTERMEDIATE_FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
CLEAR_INTERMEDIATE_FCFLAGS=$CLEAR_INTERMEDIATE_FFLAGS
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-openzwave
cp %{_builddir}/open-zwave-master/cpp/hidapi/LICENSE-bsd.txt %{buildroot}/usr/share/package-licenses/python-openzwave/7dde42b4c6fdafae722d8d07556b6d9dba4d2963 || :
cp %{_builddir}/open-zwave-master/cpp/hidapi/LICENSE-gpl3.txt %{buildroot}/usr/share/package-licenses/python-openzwave/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/open-zwave-master/cpp/hidapi/LICENSE-orig.txt %{buildroot}/usr/share/package-licenses/python-openzwave/66047dbcf3fd689c99472266f5ad141c53d6f2c6 || :
cp %{_builddir}/open-zwave-master/cpp/hidapi/LICENSE.txt %{buildroot}/usr/share/package-licenses/python-openzwave/07ee706ea70d84685d8ee57557052a7ab00c960a || :
cp %{_builddir}/open-zwave-master/debian/copyright %{buildroot}/usr/share/package-licenses/python-openzwave/c9cb6e1003d94c0123949178f34321343e9115a6 || :
cp %{_builddir}/open-zwave-master/license/Apache-License-2.0.txt %{buildroot}/usr/share/package-licenses/python-openzwave/ec55bbbac66db486cb2c8160a6dc16c98aa2a5b5 || :
cp %{_builddir}/open-zwave-master/license/gpl.txt %{buildroot}/usr/share/package-licenses/python-openzwave/2a0d409439280c8cfc806f890b757d9bd8a19a09 || :
cp %{_builddir}/open-zwave-master/license/gpl.txt %{buildroot}/usr/share/package-licenses/python-openzwave/2a0d409439280c8cfc806f890b757d9bd8a19a09 || :
cp %{_builddir}/open-zwave-master/license/license.txt %{buildroot}/usr/share/package-licenses/python-openzwave/2b26df014bec35b26b16f333522989336e24e488 || :
cp %{_builddir}/open-zwave-master/license/license.txt %{buildroot}/usr/share/package-licenses/python-openzwave/2b26df014bec35b26b16f333522989336e24e488 || :
cp %{_builddir}/python-openzwave-%{version}/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/python-openzwave/f0cb7c2c2db59bd17a620fd5070dffe7aa8acdb6 || :
cp %{_builddir}/python-openzwave-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/python-openzwave/f0cb7c2c2db59bd17a620fd5070dffe7aa8acdb6 || :
cp %{_builddir}/python-openzwave-%{version}/debian/copyright %{buildroot}/usr/share/package-licenses/python-openzwave/215fd18143ce0317e4e689997e898cfbc9b68196 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyozw_check
/usr/bin/pyozw_shell

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-openzwave/07ee706ea70d84685d8ee57557052a7ab00c960a
/usr/share/package-licenses/python-openzwave/215fd18143ce0317e4e689997e898cfbc9b68196
/usr/share/package-licenses/python-openzwave/2a0d409439280c8cfc806f890b757d9bd8a19a09
/usr/share/package-licenses/python-openzwave/2b26df014bec35b26b16f333522989336e24e488
/usr/share/package-licenses/python-openzwave/66047dbcf3fd689c99472266f5ad141c53d6f2c6
/usr/share/package-licenses/python-openzwave/7dde42b4c6fdafae722d8d07556b6d9dba4d2963
/usr/share/package-licenses/python-openzwave/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/python-openzwave/c9cb6e1003d94c0123949178f34321343e9115a6
/usr/share/package-licenses/python-openzwave/ec55bbbac66db486cb2c8160a6dc16c98aa2a5b5
/usr/share/package-licenses/python-openzwave/f0cb7c2c2db59bd17a620fd5070dffe7aa8acdb6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
